using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SDL2;
using static SDL2.SDL_image;
using static SDL2.SDL;

namespace Sdl2AsciiEngine
{
    public class Font
    {
        public enum Character
        {
            NULL,
            WHITE_SMILING_FACE,
            BLACK_SMILING_FACE,
            BLACK_HEART_SUIT,
            BLACK_DIAMOND_SUIT,
            BLACK_CLUB_SUIT,
            BLACK_SPADE_SUIT,
            BULLET,
            INVERSE_BULLET,
            WHITE_CIRCLE,
            INVERSE_WHITE_CIRCLE,
            MALE_SIGN,
            FEMALE_SIGN,
            EIGHTH_NOTE,
            BEAMED_EIGHTH_NOTES,
            WHITE_SUN_WITH_RAYS,
            BLACK_RIGHT_POINTING_POINTER,
            BLACK_LEFT_POINTING_POINTER,
            UP_DOWN_ARROW,
            DOUBLE_EXCLAMATION_MARK,
            PILCROW_SIGN,
            SECTION_SIGN,
            BLACK_RECTANGLE,
            UP_DOWN_ARROW_WITH_BASE,
            UPWARDS_ARROW,
            DOWNWARDS_ARROW,
            RIGHTWARDS_ARROW,
            LEFTWARDS_ARROW,
            RIGHT_ANGLE,
            LEFT_RIGHT_ARROW,
            BLACK_UP_POINTING_TRIANGLE,
            BLACK_DOWN_POINTING_TRIANGLE,
            SPACE,
            EXCLAMATION_MARK,
            QUOTATION_MARK,
            NUMBER_SIGN,
            DOLLAR_SIGN,
            PERCENT_SIGN,
            AMPERSAND,
            APOSTROPHE,
            LEFT_PARENTHESIS,
            RIGHT_PARENTHESIS,
            ASTERISK,
            PLUS_SIGN,
            COMMA,
            HYPHEN_MINUS,
            FULL_STOP,
            SOLIDUS,
            DIGIT_ZERO,
            DIGIT_ONE,
            DIGIT_TWO,
            DIGIT_THREE,
            DIGIT_FOUR,
            DIGIT_FIVE,
            DIGIT_SIX,
            DIGIT_SEVEN,
            DIGIT_EIGHT,
            DIGIT_NINE,
            COLON,
            SEMICOLON,
            LESS_THAN_SIGN,
            EQUALS_SIGN,
            GREATER_THAN_SIGN,
            QUESTION_MARK,
            COMMERCIAL_AT,
            LATIN_CAPITAL_LETTER_A,
            LATIN_CAPITAL_LETTER_B,
            LATIN_CAPITAL_LETTER_C,
            LATIN_CAPITAL_LETTER_D,
            LATIN_CAPITAL_LETTER_E,
            LATIN_CAPITAL_LETTER_F,
            LATIN_CAPITAL_LETTER_G,
            LATIN_CAPITAL_LETTER_H,
            LATIN_CAPITAL_LETTER_I,
            LATIN_CAPITAL_LETTER_J,
            LATIN_CAPITAL_LETTER_K,
            LATIN_CAPITAL_LETTER_L,
            LATIN_CAPITAL_LETTER_M,
            LATIN_CAPITAL_LETTER_N,
            LATIN_CAPITAL_LETTER_O,
            LATIN_CAPITAL_LETTER_P,
            LATIN_CAPITAL_LETTER_Q,
            LATIN_CAPITAL_LETTER_R,
            LATIN_CAPITAL_LETTER_S,
            LATIN_CAPITAL_LETTER_T,
            LATIN_CAPITAL_LETTER_U,
            LATIN_CAPITAL_LETTER_V,
            LATIN_CAPITAL_LETTER_W,
            LATIN_CAPITAL_LETTER_X,
            LATIN_CAPITAL_LETTER_Y,
            LATIN_CAPITAL_LETTER_Z,
            LEFT_SQUARE_BRACKET,
            REVERSE_SOLIDUS,
            RIGHT_SQUARE_BRACKET,
            CIRCUMFLEX_ACCENT,
            LOW_LINE,
            GRAVE_ACCENT,
            LATIN_SMALL_LETTER_A,
            LATIN_SMALL_LETTER_B,
            LATIN_SMALL_LETTER_C,
            LATIN_SMALL_LETTER_D,
            LATIN_SMALL_LETTER_E,
            LATIN_SMALL_LETTER_F,
            LATIN_SMALL_LETTER_G,
            LATIN_SMALL_LETTER_H,
            LATIN_SMALL_LETTER_I,
            LATIN_SMALL_LETTER_J,
            LATIN_SMALL_LETTER_K,
            LATIN_SMALL_LETTER_L,
            LATIN_SMALL_LETTER_M,
            LATIN_SMALL_LETTER_N,
            LATIN_SMALL_LETTER_O,
            LATIN_SMALL_LETTER_P,
            LATIN_SMALL_LETTER_Q,
            LATIN_SMALL_LETTER_R,
            LATIN_SMALL_LETTER_S,
            LATIN_SMALL_LETTER_T,
            LATIN_SMALL_LETTER_U,
            LATIN_SMALL_LETTER_V,
            LATIN_SMALL_LETTER_W,
            LATIN_SMALL_LETTER_X,
            LATIN_SMALL_LETTER_Y,
            LATIN_SMALL_LETTER_Z,
            LEFT_CURLY_BRACKET,
            VERTICAL_LINE,
            RIGHT_CURLY_BRACKET,
            TILDE,
            HOUSE,
            LATIN_CAPITAL_LETTER_C_WITH_CEDILLA,
            LATIN_SMALL_LETTER_U_WITH_DIAERESIS,
            LATIN_SMALL_LETTER_E_WITH_ACUTE,
            LATIN_SMALL_LETTER_A_WITH_CIRCUMFLEX,
            LATIN_SMALL_LETTER_A_WITH_DIAERESIS,
            LATIN_SMALL_LETTER_A_WITH_GRAVE,
            LATIN_SMALL_LETTER_A_WITH_RING_ABOVE,
            LATIN_SMALL_LETTER_C_WITH_CEDILLA,
            LATIN_SMALL_LETTER_E_WITH_CIRCUMFLEX,
            LATIN_SMALL_LETTER_E_WITH_DIAERESIS,
            LATIN_SMALL_LETTER_E_WITH_GRAVE,
            LATIN_SMALL_LETTER_I_WITH_DIAERESIS,
            LATIN_SMALL_LETTER_I_WITH_CIRCUMFLEX,
            LATIN_SMALL_LETTER_I_WITH_GRAVE,
            LATIN_CAPITAL_LETTER_A_WITH_DIAERESIS,
            LATIN_CAPITAL_LETTER_A_WITH_RING_ABOVE,
            LATIN_CAPITAL_LETTER_E_WITH_ACUTE,
            LATIN_SMALL_LETTER_AE,
            LATIN_CAPITAL_LETTER_AE,
            LATIN_SMALL_LETTER_O_WITH_CIRCUMFLEX,
            LATIN_SMALL_LETTER_O_WITH_DIAERESIS,
            LATIN_SMALL_LETTER_O_WITH_GRAVE,
            LATIN_SMALL_LETTER_U_WITH_CIRCUMFLEX,
            LATIN_SMALL_LETTER_U_WITH_GRAVE,
            LATIN_SMALL_LETTER_Y_WITH_DIAERESIS,
            LATIN_CAPITAL_LETTER_O_WITH_DIAERESIS,
            LATIN_CAPITAL_LETTER_U_WITH_DIAERESIS,
            CENT_SIGN,
            POUND_SIGN,
            YEN_SIGN,
            PESETA_SIGN,
            LATIN_SMALL_LETTER_F_WITH_HOOK,
            LATIN_SMALL_LETTER_A_WITH_ACUTE,
            LATIN_SMALL_LETTER_I_WITH_ACUTE,
            LATIN_SMALL_LETTER_O_WITH_ACUTE,
            LATIN_SMALL_LETTER_U_WITH_ACUTE,
            LATIN_SMALL_LETTER_N_WITH_TILDE,
            LATIN_CAPITAL_LETTER_N_WITH_TILDE,
            FEMININE_ORDINAL_INDICATOR,
            MASCULINE_ORDINAL_INDICATOR,
            INVERTED_QUESTION_MARK,
            REVERSED_NOT_SIGN,
            NOT_SIGN,
            VULGAR_FRACTION_ONE_HALF,
            VULGAR_FRACTION_ONE_QUARTER,
            INVERTED_EXCLAMATION_MARK,
            LEFT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK,
            RIGHT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK,
            LIGHT_SHADE,
            MEDIUM_SHADE,
            DARK_SHADE,
            BOX_DRAWINGS_LIGHT_VERTICAL,
            BOX_DRAWINGS_LIGHT_VERTICAL_AND_LEFT,
            BOX_DRAWINGS_VERTICAL_SINGLE_AND_LEFT_DOUBLE,
            BOX_DRAWINGS_VERTICAL_DOUBLE_AND_LEFT_SINGLE,
            BOX_DRAWINGS_DOWN_DOUBLE_AND_LEFT_SINGLE,
            BOX_DRAWINGS_DOWN_SINGLE_AND_LEFT_DOUBLE,
            BOX_DRAWINGS_DOUBLE_VERTICAL_AND_LEFT,
            BOX_DRAWINGS_DOUBLE_VERTICAL,
            BOX_DRAWINGS_DOUBLE_DOWN_AND_LEFT,
            BOX_DRAWINGS_DOUBLE_UP_AND_LEFT,
            BOX_DRAWINGS_UP_DOUBLE_AND_LEFT_SINGLE,
            BOX_DRAWINGS_UP_SINGLE_AND_LEFT_DOUBLE,
            BOX_DRAWINGS_LIGHT_DOWN_AND_LEFT,
            BOX_DRAWINGS_LIGHT_UP_AND_RIGHT,
            BOX_DRAWINGS_LIGHT_UP_AND_HORIZONTAL,
            BOX_DRAWINGS_LIGHT_DOWN_AND_HORIZONTAL,
            BOX_DRAWINGS_LIGHT_VERTICAL_AND_RIGHT,
            BOX_DRAWINGS_LIGHT_HORIZONTAL,
            BOX_DRAWINGS_LIGHT_VERTICAL_AND_HORIZONTAL,
            BOX_DRAWINGS_VERTICAL_SINGLE_AND_RIGHT_DOUBLE,
            BOX_DRAWINGS_VERTICAL_DOUBLE_AND_RIGHT_SINGLE,
            BOX_DRAWINGS_DOUBLE_UP_AND_RIGHT,
            BOX_DRAWINGS_DOUBLE_DOWN_AND_RIGHT,
            BOX_DRAWINGS_DOUBLE_UP_AND_HORIZONTAL,
            BOX_DRAWINGS_DOUBLE_DOWN_AND_HORIZONTAL,
            BOX_DRAWINGS_DOUBLE_VERTICAL_AND_RIGHT,
            BOX_DRAWINGS_DOUBLE_HORIZONTAL,
            BOX_DRAWINGS_DOUBLE_VERTICAL_AND_HORIZONTAL,
            BOX_DRAWINGS_UP_SINGLE_AND_HORIZONTAL_DOUBLE,
            BOX_DRAWINGS_UP_DOUBLE_AND_HORIZONTAL_SINGLE,
            BOX_DRAWINGS_DOWN_SINGLE_AND_HORIZONTAL_DOUBLE,
            BOX_DRAWINGS_DOWN_DOUBLE_AND_HORIZONTAL_SINGLE,
            BOX_DRAWINGS_UP_DOUBLE_AND_RIGHT_SINGLE,
            BOX_DRAWINGS_UP_SINGLE_AND_RIGHT_DOUBLE,
            BOX_DRAWINGS_DOWN_SINGLE_AND_RIGHT_DOUBLE,
            BOX_DRAWINGS_DOWN_DOUBLE_AND_RIGHT_SINGLE,
            BOX_DRAWINGS_VERTICAL_DOUBLE_AND_HORIZONTAL_SINGLE,
            BOX_DRAWINGS_VERTICAL_SINGLE_AND_HORIZONTAL_DOUBLE,
            BOX_DRAWINGS_LIGHT_UP_AND_LEFT,
            BOX_DRAWINGS_LIGHT_DOWN_AND_RIGHT,
            FULL_BLOCK,
            LOWER_HALF_BLOCK,
            LEFT_HALF_BLOCK,
            RIGHT_HALF_BLOCK,
            UPPER_HALF_BLOCK,
            GREEK_SMALL_LETTER_ALPHA,
            LATIN_SMALL_LETTER_SHARP_S,
            GREEK_CAPITAL_LETTER_GAMMA,
            GREEK_SMALL_LETTER_PI,
            GREEK_CAPITAL_LETTER_SIGMA,
            GREEK_SMALL_LETTER_SIGMA,
            MICRO_SIGN,
            GREEK_SMALL_LETTER_TAU,
            GREEK_CAPITAL_LETTER_PHI,
            GREEK_CAPITAL_LETTER_THETA,
            GREEK_CAPITAL_LETTER_OMEGA,
            GREEK_SMALL_LETTER_DELTA,
            INFINITY,
            GREEK_SMALL_LETTER_PHI,
            GREEK_SMALL_LETTER_EPSILON,
            INTERSECTION,
            IDENTICAL_TO,
            PLUS_MINUS_SIGN,
            GREATER_THAN_OR_EQUAL_TO,
            LESS_THAN_OR_EQUAL_TO,
            TOP_HALF_INTEGRAL,
            BOTTOM_HALF_INTEGRAL,
            DIVISION_SIGN,
            ALMOST_EQUAL_TO,
            DEGREE_SIGN,
            BULLET_OPERATOR,
            MIDDLE_DOT,
            SQUARE_ROOT,
            SUPERSCRIPT_LATIN_SMALL_LETTER_N,
            SUPERSCRIPT_TWO,
            BLACK_SQUARE,
            NO_BREAK_SPACE,

        }
        struct unicode_t
        {
            public char symbol;
            public char ascii;
            public string name;
            public unicode_t(char symbol, char ascii, string name)
            {
                this.symbol = symbol;
                this.ascii = ascii;
                this.name = name;
            }
        };
        public string Output()
        {
            string output = "";
            foreach (unicode_t t in table)
            {
                output+= (t.name.Replace(" ","_") + ",\n");
            }
            return output;
        }
        
        public static int[] TilesFromString(string str)
        {
            int[] tiles = new int[str.Length];
            int i = 0;
            foreach (char c in str)
            {
                tiles[i] = CharToIndex(c);
                i++;
            }
            return tiles;
        }
        public static int CharToIndex(char c)
        {
            int i = 0;
            foreach (unicode_t t in table)
            {
                if (t.symbol == c)
                {
                    return i;
                }
                i++;
            }
            return 0;
        }

        static unicode_t[] table = new unicode_t[]{
            new unicode_t( '\u0000', '\u0000', "NULL" ),
            new unicode_t('\u263A', '\u0000', "WHITE SMILING FACE" ),
            new unicode_t('\u263B', '\u0000', "BLACK SMILING FACE" ),
            new unicode_t('\u2665', '\u0000', "BLACK HEART SUIT" ),
            new unicode_t('\u2666', '\u0000', "BLACK DIAMOND SUIT" ),
            new unicode_t('\u2663', '\u0000', "BLACK CLUB SUIT" ),
            new unicode_t('\u2660', '\u0000', "BLACK SPADE SUIT" ),
            new unicode_t('\u2022', '\u0000', "BULLET" ),
            new unicode_t('\u25D8', '\u0000', "INVERSE BULLET" ),
            new unicode_t('\u25CB', '\u0000', "WHITE CIRCLE" ),
            new unicode_t('\u25D9', '\u0000', "INVERSE WHITE CIRCLE" ),
            new unicode_t('\u2642', '\u0000', "MALE SIGN" ),
            new unicode_t('\u2640', '\u0000', "FEMALE SIGN" ),
            new unicode_t('\u266A', '\u0000', "EIGHTH NOTE" ),
            new unicode_t('\u266B', '\u0000', "BEAMED EIGHTH NOTES" ),
            new unicode_t('\u263C', '\u0000', "WHITE SUN WITH RAYS" ),
            new unicode_t('\u25BA', '\u0000', "BLACK RIGHT-POINTING POINTER" ),
            new unicode_t('\u25C4', '\u0000', "BLACK LEFT-POINTING POINTER" ),
            new unicode_t('\u2195', '\u0000', "UP DOWN ARROW" ),
            new unicode_t('\u203C', '\u0000', "DOUBLE EXCLAMATION MARK" ),
            new unicode_t('\u00B6', '\u0000', "PILCROW SIGN" ),
            new unicode_t('\u00A7', '\u0000', "SECTION SIGN" ),
            new unicode_t('\u25AC', '\u0000', "BLACK RECTANGLE" ),
            new unicode_t('\u21A8', '\u0000', "UP DOWN ARROW WITH BASE" ),
            new unicode_t('\u2191', '\u0000', "UPWARDS ARROW" ),
            new unicode_t('\u2193', '\u0000', "DOWNWARDS ARROW" ),
            new unicode_t('\u2192', '\u0000', "RIGHTWARDS ARROW" ),
            new unicode_t('\u2190', '\u0000', "LEFTWARDS ARROW" ),
            new unicode_t('\u221F', '\u0000', "RIGHT ANGLE" ),
            new unicode_t('\u2194', '\u0000', "LEFT RIGHT ARROW" ),
            new unicode_t('\u25B2', '\u0000', "BLACK UP-POINTING TRIANGLE" ),
            new unicode_t('\u25BC', '\u0000', "BLACK DOWN-POINTING TRIANGLE" ),
            new unicode_t('\u0020', '\u0000', "SPACE" ),
            new unicode_t('\u0021', '!', "EXCLAMATION MARK" ),
            new unicode_t('\u0022', '"', "QUOTATION MARK" ),
            new unicode_t('\u0023', '#', "NUMBER SIGN" ),
            new unicode_t('\u0024', '$', "DOLLAR SIGN" ),
            new unicode_t('\u0025', '%', "PERCENT SIGN" ),
            new unicode_t('\u0026', '&', "AMPERSAND" ),
            new unicode_t('\u0027', '\'', "APOSTROPHE" ),
            new unicode_t('\u0028', '(', "LEFT PARENTHESIS" ),
            new unicode_t('\u0029', ')', "RIGHT PARENTHESIS" ),
            new unicode_t('\u002A', '*', "ASTERISK" ),
            new unicode_t('\u002B', '+', "PLUS SIGN" ),
            new unicode_t('\u002C', ',', "COMMA" ),
            new unicode_t('\u002D', '-', "HYPHEN-MINUS" ),
            new unicode_t('\u002E', '.', "FULL STOP" ),
            new unicode_t('\u002F', '/', "SOLIDUS" ),
            new unicode_t('\u0030', '0', "DIGIT ZERO" ),
            new unicode_t('\u0031', '1', "DIGIT ONE" ),
            new unicode_t('\u0032', '2', "DIGIT TWO" ),
            new unicode_t('\u0033', '3', "DIGIT THREE" ),
            new unicode_t('\u0034', '4', "DIGIT FOUR" ),
            new unicode_t('\u0035', '5', "DIGIT FIVE" ),
            new unicode_t('\u0036', '6', "DIGIT SIX" ),
            new unicode_t('\u0037', '7', "DIGIT SEVEN" ),
            new unicode_t('\u0038', '8', "DIGIT EIGHT" ),
            new unicode_t('\u0039', '9', "DIGIT NINE" ),
            new unicode_t('\u003A', ':', "COLON" ),
            new unicode_t('\u003B', ';', "SEMICOLON" ),
            new unicode_t('\u003C', '<', "LESS-THAN SIGN" ),
            new unicode_t('\u003D', '=', "EQUALS SIGN" ),
            new unicode_t('\u003E', '>', "GREATER-THAN SIGN" ),
            new unicode_t('\u003F', '?', "QUESTION MARK" ),
            new unicode_t('\u0040', '@', "COMMERCIAL AT" ),
            new unicode_t('\u0041', 'A', "LATIN CAPITAL LETTER A" ),
            new unicode_t('\u0042', 'B', "LATIN CAPITAL LETTER B" ),
            new unicode_t('\u0043', 'C', "LATIN CAPITAL LETTER C" ),
            new unicode_t('\u0044', 'D', "LATIN CAPITAL LETTER D" ),
            new unicode_t('\u0045', 'E', "LATIN CAPITAL LETTER E" ),
            new unicode_t('\u0046', 'F', "LATIN CAPITAL LETTER F" ),
            new unicode_t('\u0047', 'G', "LATIN CAPITAL LETTER G" ),
            new unicode_t('\u0048', 'H', "LATIN CAPITAL LETTER H" ),
            new unicode_t('\u0049', 'I', "LATIN CAPITAL LETTER I" ),
            new unicode_t('\u004A', 'J', "LATIN CAPITAL LETTER J" ),
            new unicode_t('\u004B', 'K', "LATIN CAPITAL LETTER K" ),
            new unicode_t('\u004C', 'L', "LATIN CAPITAL LETTER L" ),
            new unicode_t('\u004D', 'M', "LATIN CAPITAL LETTER M" ),
            new unicode_t('\u004E', 'N', "LATIN CAPITAL LETTER N" ),
            new unicode_t('\u004F', 'O', "LATIN CAPITAL LETTER O" ),
            new unicode_t('\u0050', 'P', "LATIN CAPITAL LETTER P" ),
            new unicode_t('\u0051', 'Q', "LATIN CAPITAL LETTER Q" ),
            new unicode_t('\u0052', 'R', "LATIN CAPITAL LETTER R" ),
            new unicode_t('\u0053', 'S', "LATIN CAPITAL LETTER S" ),
            new unicode_t('\u0054', 'T', "LATIN CAPITAL LETTER T" ),
            new unicode_t('\u0055', 'U', "LATIN CAPITAL LETTER U" ),
            new unicode_t('\u0056', 'V', "LATIN CAPITAL LETTER V" ),
            new unicode_t('\u0057', 'W', "LATIN CAPITAL LETTER W" ),
            new unicode_t('\u0058', 'X', "LATIN CAPITAL LETTER X" ),
            new unicode_t('\u0059', 'Y', "LATIN CAPITAL LETTER Y" ),
            new unicode_t('\u005A', 'Z', "LATIN CAPITAL LETTER Z" ),
            new unicode_t('\u005B', '[', "LEFT SQUARE BRACKET" ),
            new unicode_t('\u005C', '\\', "REVERSE SOLIDUS" ),
            new unicode_t('\u005D', ']', "RIGHT SQUARE BRACKET" ),
            new unicode_t('\u005E', '^', "CIRCUMFLEX ACCENT" ),
            new unicode_t('\u005F', '_', "LOW LINE" ),
            new unicode_t('\u0060', '`', "GRAVE ACCENT" ),
            new unicode_t('\u0061', 'a', "LATIN SMALL LETTER A" ),
            new unicode_t('\u0062', 'b', "LATIN SMALL LETTER B" ),
            new unicode_t('\u0063', 'c', "LATIN SMALL LETTER C" ),
            new unicode_t('\u0064', 'd', "LATIN SMALL LETTER D" ),
            new unicode_t('\u0065', 'e', "LATIN SMALL LETTER E" ),
            new unicode_t('\u0066', 'f', "LATIN SMALL LETTER F" ),
            new unicode_t('\u0067', 'g', "LATIN SMALL LETTER G" ),
            new unicode_t('\u0068', 'h', "LATIN SMALL LETTER H" ),
            new unicode_t('\u0069', 'i', "LATIN SMALL LETTER I" ),
            new unicode_t('\u006A', 'j', "LATIN SMALL LETTER J" ),
            new unicode_t('\u006B', 'k', "LATIN SMALL LETTER K" ),
            new unicode_t('\u006C', 'l', "LATIN SMALL LETTER L" ),
            new unicode_t('\u006D', 'm', "LATIN SMALL LETTER M" ),
            new unicode_t('\u006E', 'n', "LATIN SMALL LETTER N" ),
            new unicode_t('\u006F', 'o', "LATIN SMALL LETTER O" ),
            new unicode_t('\u0070', 'p', "LATIN SMALL LETTER P" ),
            new unicode_t('\u0071', 'q', "LATIN SMALL LETTER Q" ),
            new unicode_t('\u0072', 'r', "LATIN SMALL LETTER R" ),
            new unicode_t('\u0073', 's', "LATIN SMALL LETTER S" ),
            new unicode_t('\u0074', 't', "LATIN SMALL LETTER T" ),
            new unicode_t('\u0075', 'u', "LATIN SMALL LETTER U" ),
            new unicode_t('\u0076', 'v', "LATIN SMALL LETTER V" ),
            new unicode_t('\u0077', 'w', "LATIN SMALL LETTER W" ),
            new unicode_t('\u0078', 'x', "LATIN SMALL LETTER X" ),
            new unicode_t('\u0079', 'y', "LATIN SMALL LETTER Y" ),
            new unicode_t('\u007A', 'z', "LATIN SMALL LETTER Z" ),
            new unicode_t('\u007B', '{', "LEFT CURLY BRACKET" ),
            new unicode_t('\u007C', '|', "VERTICAL LINE" ),
            new unicode_t('\u007D', '}', "RIGHT CURLY BRACKET" ),
            new unicode_t('\u007E', '~', "TILDE" ),

            new unicode_t('\u2302', '\u0000', "HOUSE" ),

            new unicode_t('\u00C7', '\u0000', "LATIN CAPITAL LETTER C WITH CEDILLA" ),
            new unicode_t('\u00FC', '\u0000', "LATIN SMALL LETTER U WITH DIAERESIS" ),
            new unicode_t('\u00E9', '\u0000', "LATIN SMALL LETTER E WITH ACUTE" ),
            new unicode_t('\u00E2', '\u0000', "LATIN SMALL LETTER A WITH CIRCUMFLEX" ),
            new unicode_t('\u00E4', '\u0000', "LATIN SMALL LETTER A WITH DIAERESIS" ),
            new unicode_t('\u00E0', '\u0000', "LATIN SMALL LETTER A WITH GRAVE" ),
            new unicode_t('\u00E5', '\u0000', "LATIN SMALL LETTER A WITH RING ABOVE" ),
            new unicode_t('\u00E7', '\u0000', "LATIN SMALL LETTER C WITH CEDILLA" ),
            new unicode_t('\u00EA', '\u0000', "LATIN SMALL LETTER E WITH CIRCUMFLEX" ),
            new unicode_t('\u00EB', '\u0000', "LATIN SMALL LETTER E WITH DIAERESIS" ),
            new unicode_t('\u00E8', '\u0000', "LATIN SMALL LETTER E WITH GRAVE" ),
            new unicode_t('\u00EF', '\u0000', "LATIN SMALL LETTER I WITH DIAERESIS" ),
            new unicode_t('\u00EE', '\u0000', "LATIN SMALL LETTER I WITH CIRCUMFLEX" ),
            new unicode_t('\u00EC', '\u0000', "LATIN SMALL LETTER I WITH GRAVE" ),
            new unicode_t('\u00C4', '\u0000', "LATIN CAPITAL LETTER A WITH DIAERESIS" ),
            new unicode_t('\u00C5', '\u0000', "LATIN CAPITAL LETTER A WITH RING ABOVE" ),
            new unicode_t('\u00C9', '\u0000', "LATIN CAPITAL LETTER E WITH ACUTE" ),
            new unicode_t('\u00E6', '\u0000', "LATIN SMALL LETTER AE" ),
            new unicode_t('\u00C6', '\u0000', "LATIN CAPITAL LETTER AE" ),
            new unicode_t('\u00F4', '\u0000', "LATIN SMALL LETTER O WITH CIRCUMFLEX" ),
            new unicode_t('\u00F6', '\u0000', "LATIN SMALL LETTER O WITH DIAERESIS" ),
            new unicode_t('\u00F2', '\u0000', "LATIN SMALL LETTER O WITH GRAVE" ),
            new unicode_t('\u00FB', '\u0000', "LATIN SMALL LETTER U WITH CIRCUMFLEX" ),
            new unicode_t('\u00F9', '\u0000', "LATIN SMALL LETTER U WITH GRAVE" ),
            new unicode_t('\u00FF', '\u0000', "LATIN SMALL LETTER Y WITH DIAERESIS" ),
            new unicode_t('\u00D6', '\u0000', "LATIN CAPITAL LETTER O WITH DIAERESIS" ),
            new unicode_t('\u00DC', '\u0000', "LATIN CAPITAL LETTER U WITH DIAERESIS" ),
            new unicode_t('\u00A2', '\u0000', "CENT SIGN" ),
            new unicode_t('\u00A3', '\u0000', "POUND SIGN" ),
            new unicode_t('\u00A5', '\u0000', "YEN SIGN" ),
            new unicode_t('\u20A7', '\u0000', "PESETA SIGN" ),
            new unicode_t('\u0192', '\u0000', "LATIN SMALL LETTER F WITH HOOK" ),
            new unicode_t('\u00E1', '\u0000', "LATIN SMALL LETTER A WITH ACUTE" ),
            new unicode_t('\u00ED', '\u0000', "LATIN SMALL LETTER I WITH ACUTE" ),
            new unicode_t('\u00F3', '\u0000', "LATIN SMALL LETTER O WITH ACUTE" ),
            new unicode_t('\u00FA', '\u0000', "LATIN SMALL LETTER U WITH ACUTE" ),
            new unicode_t('\u00F1', '\u0000', "LATIN SMALL LETTER N WITH TILDE" ),
            new unicode_t('\u00D1', '\u0000', "LATIN CAPITAL LETTER N WITH TILDE" ),
            new unicode_t('\u00AA', '\u0000', "FEMININE ORDINAL INDICATOR" ),
            new unicode_t('\u00BA', '\u0000', "MASCULINE ORDINAL INDICATOR" ),
            new unicode_t('\u00BF', '\u0000', "INVERTED QUESTION MARK" ),
            new unicode_t('\u2310', '\u0000', "REVERSED NOT SIGN" ),
            new unicode_t('\u00AC', '\u0000', "NOT SIGN" ),
            new unicode_t('\u00BD', '\u0000', "VULGAR FRACTION ONE HALF" ),
            new unicode_t('\u00BC', '\u0000', "VULGAR FRACTION ONE QUARTER" ),
            new unicode_t('\u00A1', '\u0000', "INVERTED EXCLAMATION MARK" ),
            new unicode_t('\u00AB', '\u0000', "LEFT-POINTING DOUBLE ANGLE QUOTATION MARK" ),
            new unicode_t('\u00BB', '\u0000', "RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK" ),
            new unicode_t('\u2591', '\u0000', "LIGHT SHADE" ),
            new unicode_t('\u2592', '\u0000', "MEDIUM SHADE" ),
            new unicode_t('\u2593', '\u0000', "DARK SHADE" ),
            new unicode_t('\u2502', '\u0000', "BOX DRAWINGS LIGHT VERTICAL" ),
            new unicode_t('\u2524', '\u0000', "BOX DRAWINGS LIGHT VERTICAL AND LEFT" ),
            new unicode_t('\u2561', '\u0000', "BOX DRAWINGS VERTICAL SINGLE AND LEFT DOUBLE" ),
            new unicode_t('\u2562', '\u0000', "BOX DRAWINGS VERTICAL DOUBLE AND LEFT SINGLE" ),
            new unicode_t('\u2556', '\u0000', "BOX DRAWINGS DOWN DOUBLE AND LEFT SINGLE" ),
            new unicode_t('\u2555', '\u0000', "BOX DRAWINGS DOWN SINGLE AND LEFT DOUBLE" ),
            new unicode_t('\u2563', '\u0000', "BOX DRAWINGS DOUBLE VERTICAL AND LEFT" ),
            new unicode_t('\u2551', '\u0000', "BOX DRAWINGS DOUBLE VERTICAL" ),
            new unicode_t('\u2557', '\u0000', "BOX DRAWINGS DOUBLE DOWN AND LEFT" ),
            new unicode_t('\u255D', '\u0000', "BOX DRAWINGS DOUBLE UP AND LEFT" ),
            new unicode_t('\u255C', '\u0000', "BOX DRAWINGS UP DOUBLE AND LEFT SINGLE" ),
            new unicode_t('\u255B', '\u0000', "BOX DRAWINGS UP SINGLE AND LEFT DOUBLE" ),
            new unicode_t('\u2510', '\u0000', "BOX DRAWINGS LIGHT DOWN AND LEFT" ),
            new unicode_t('\u2514', '\u0000', "BOX DRAWINGS LIGHT UP AND RIGHT" ),
            new unicode_t('\u2534', '\u0000', "BOX DRAWINGS LIGHT UP AND HORIZONTAL" ),
            new unicode_t('\u252C', '\u0000', "BOX DRAWINGS LIGHT DOWN AND HORIZONTAL" ),
            new unicode_t('\u251C', '\u0000', "BOX DRAWINGS LIGHT VERTICAL AND RIGHT" ),
            new unicode_t('\u2500', '\u0000', "BOX DRAWINGS LIGHT HORIZONTAL" ),
            new unicode_t('\u253C', '\u0000', "BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL" ),
            new unicode_t('\u255E', '\u0000', "BOX DRAWINGS VERTICAL SINGLE AND RIGHT DOUBLE" ),
            new unicode_t('\u255F', '\u0000', "BOX DRAWINGS VERTICAL DOUBLE AND RIGHT SINGLE" ),
            new unicode_t('\u255A', '\u0000', "BOX DRAWINGS DOUBLE UP AND RIGHT" ),
            new unicode_t('\u2554', '\u0000', "BOX DRAWINGS DOUBLE DOWN AND RIGHT" ),
            new unicode_t('\u2569', '\u0000', "BOX DRAWINGS DOUBLE UP AND HORIZONTAL" ),
            new unicode_t('\u2566', '\u0000', "BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL" ),
            new unicode_t('\u2560', '\u0000', "BOX DRAWINGS DOUBLE VERTICAL AND RIGHT" ),
            new unicode_t('\u2550', '\u0000', "BOX DRAWINGS DOUBLE HORIZONTAL" ),
            new unicode_t('\u256C', '\u0000', "BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL" ),
            new unicode_t('\u2567', '\u0000', "BOX DRAWINGS UP SINGLE AND HORIZONTAL DOUBLE" ),
            new unicode_t('\u2568', '\u0000', "BOX DRAWINGS UP DOUBLE AND HORIZONTAL SINGLE" ),
            new unicode_t('\u2564', '\u0000', "BOX DRAWINGS DOWN SINGLE AND HORIZONTAL DOUBLE" ),
            new unicode_t('\u2565', '\u0000', "BOX DRAWINGS DOWN DOUBLE AND HORIZONTAL SINGLE" ),
            new unicode_t('\u2559', '\u0000', "BOX DRAWINGS UP DOUBLE AND RIGHT SINGLE" ),
            new unicode_t('\u2558', '\u0000', "BOX DRAWINGS UP SINGLE AND RIGHT DOUBLE" ),
            new unicode_t('\u2552', '\u0000', "BOX DRAWINGS DOWN SINGLE AND RIGHT DOUBLE" ),
            new unicode_t('\u2553', '\u0000', "BOX DRAWINGS DOWN DOUBLE AND RIGHT SINGLE" ),
            new unicode_t('\u256B', '\u0000', "BOX DRAWINGS VERTICAL DOUBLE AND HORIZONTAL SINGLE" ),
            new unicode_t('\u256A', '\u0000', "BOX DRAWINGS VERTICAL SINGLE AND HORIZONTAL DOUBLE" ),
            new unicode_t('\u2518', '\u0000', "BOX DRAWINGS LIGHT UP AND LEFT" ),
            new unicode_t('\u250C', '\u0000', "BOX DRAWINGS LIGHT DOWN AND RIGHT" ),
            new unicode_t('\u2588', '\u0000', "FULL BLOCK" ),
            new unicode_t('\u2584', '\u0000', "LOWER HALF BLOCK" ),
            new unicode_t('\u258C', '\u0000', "LEFT HALF BLOCK" ),
            new unicode_t('\u2590', '\u0000', "RIGHT HALF BLOCK" ),
            new unicode_t('\u2580', '\u0000', "UPPER HALF BLOCK" ),
            new unicode_t('\u03B1', '\u0000', "GREEK SMALL LETTER ALPHA" ),
            new unicode_t('\u00DF', '\u0000', "LATIN SMALL LETTER SHARP S" ),
            new unicode_t('\u0393', '\u0000', "GREEK CAPITAL LETTER GAMMA" ),
            new unicode_t('\u03C0', '\u0000', "GREEK SMALL LETTER PI" ),
            new unicode_t('\u03A3', '\u0000', "GREEK CAPITAL LETTER SIGMA" ),
            new unicode_t('\u03C3', '\u0000', "GREEK SMALL LETTER SIGMA" ),
            new unicode_t('\u00B5', '\u0000', "MICRO SIGN" ),
            new unicode_t('\u03C4', '\u0000', "GREEK SMALL LETTER TAU" ),
            new unicode_t('\u03A6', '\u0000', "GREEK CAPITAL LETTER PHI" ),
            new unicode_t('\u0398', '\u0000', "GREEK CAPITAL LETTER THETA" ),
            new unicode_t('\u03A9', '\u0000', "GREEK CAPITAL LETTER OMEGA" ),
            new unicode_t('\u03B4', '\u0000', "GREEK SMALL LETTER DELTA" ),
            new unicode_t('\u221E', '\u0000', "INFINITY" ),
            new unicode_t('\u03C6', '\u0000', "GREEK SMALL LETTER PHI" ),
            new unicode_t('\u03B5', '\u0000', "GREEK SMALL LETTER EPSILON" ),
            new unicode_t('\u2229', '\u0000', "INTERSECTION" ),
            new unicode_t('\u2261', '\u0000', "IDENTICAL TO" ),
            new unicode_t('\u00B1', '\u0000', "PLUS-MINUS SIGN" ),
            new unicode_t('\u2265', '\u0000', "GREATER-THAN OR EQUAL TO" ),
            new unicode_t('\u2264', '\u0000', "LESS-THAN OR EQUAL TO" ),
            new unicode_t('\u2320', '\u0000', "TOP HALF INTEGRAL" ),
            new unicode_t('\u2321', '\u0000', "BOTTOM HALF INTEGRAL" ),
            new unicode_t('\u00F7', '\u0000', "DIVISION SIGN" ),
            new unicode_t('\u2248', '\u0000', "ALMOST EQUAL TO" ),
            new unicode_t('\u00B0', '\u0000', "DEGREE SIGN" ),
            new unicode_t('\u2219', '\u0000', "BULLET OPERATOR" ),
            new unicode_t('\u00B7', '\u0000', "MIDDLE DOT" ),
            new unicode_t('\u221A', '\u0000', "SQUARE ROOT" ),
            new unicode_t('\u207F', '\u0000', "SUPERSCRIPT LATIN SMALL LETTER N" ),
            new unicode_t('\u00B2', '\u0000', "SUPERSCRIPT TWO" ),
            new unicode_t('\u25A0', '\u0000', "BLACK SQUARE" ),

            new unicode_t('\u00A0', '\u0000', "NO-BREAK SPACE")

        };
    }
}
